# Generated by Django 2.2 on 2022-01-15 21:03

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('base_img', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('MO', 'Mobiles'), ('CO', 'Computers'), ('CA', 'Computer accessories'), ('TV', 'TV'), ('AP', 'Appliances'), ('EL', 'Electronics'), ('FA', 'Fashion'), ('HO', 'Home'), ('KI', 'Kitchen'), ('PE', 'Pets'), ('BE', 'Beauty'), ('GR', 'Grocery'), ('SP', 'Sports'), ('FI', 'Fitness'), ('BL', 'Bags and Luggage'), ('TB', 'Toys and Baby products'), ('AU', 'Automobile'), ('IN', 'Industrial'), ('BK', 'Books'), ('MO', 'Movies'), ('MU', 'Music'), ('VG', 'Video Games')], max_length=100, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('vendor', models.CharField(max_length=150)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('guarantee', models.IntegerField()),
                ('colors', models.CharField(max_length=300, null=True)),
                ('reviews', djongo.models.fields.JSONField()),
                ('rating', models.FloatField(default=0)),
                ('no_of_ratings', models.BigIntegerField(default=0)),
                ('extra_details', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('is_vendor', models.BooleanField(default=False)),
                ('cart_items', djongo.models.fields.JSONField(null=True)),
                ('wish_list', djongo.models.fields.JSONField(null=True)),
                ('details', djongo.models.fields.JSONField(null=True)),
                ('products', djongo.models.fields.JSONField(null=True)),
                ('GSTIN', models.CharField(max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
